name: Build-app

on: [workflow_dispatch]

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller main.py --noconfirm --onefile --windowed --name "build" &&
                mv assets dist/build.app/Contents/Resources/assets &&
                cd dist/ &&
                zip -r9 build build.app/
            OUT_FILE_NAME: mac-build.zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller main.py --noconfirm --onefile --windowed --name "build" &&
                mv -Path ./assets -Destination ./dist/assets &&
                Compress-Archive -Path './dist' -DestinationPath './dist/win-zip.zip'
            OUT_FILE_NAME: win-build.zip
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pygame
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.OUT_FILE_NAME}}
        path: ./dist/${{ matrix.OUT_FILE_NAME}}