# This is a basic workflow to help you get started with Actions

name: test-game

# Controls when the workflow will run
on:
  push:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: deployment 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.10.2

      - name: Get pygame
        run: python -m pip install pygame

      - name: Get pytest
        run: python -m pip install -U pytest
        
      # - name: Run Game
      #   run: python main.py

      - name: Test game functions
        run: pytest test_game.py
